version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    links:
      - postgres
    depends_on:
      - postgres
    tty: true
    restart: always
    volumes:
      - .:/go/src/github.com/naoki/task
    command: go run main.go
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - 5432:5432
    tty: true
    restart: always
