version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      TZ: /usr/share/zoneinfo/Europe/Kiev
      GO111MODULE: "on"
    working_directory: /go/src/github.com/naoki/gacha
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get -v -t -d ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Test
          command: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
